packages:
  - apps/*
  - packages/*

allowBuilds:
  dtrace-provider: false
  esbuild: false
  protobufjs: false
  sharp: false
  workerd: false

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
